### ISSUE TITLE
[CY-2520] File by file testing creates incorrect warnings.

### ISSUE THREAD

**Issue by git-ruttmann** [codacy/codacy-sonar-csharp#71]
An interface is defined in a separte file. A unittest has a mocked implementation of that interface, with parts of the mock throwing a `NotImplementedException`.

Using codacy, sonar warns S1144 (remove unused member) and S2325 (make implementation static) for the not implemented members. Both are false positives as the member must be there and it cannot be static.

The warning doesn't occur with the sonar plugin for visual studio.

I've tracked that down to the fact, that codacy-sonar-csharp creates a new solution for each file, so effectively it's a file by file and not a solution wide analysis. As the interface definition is not present, the sonar analyzer treats the interface as empty and then the reported error makes sense.

The [false positive in my solution](https://app.codacy.com/manual/git-ruttmann/PolygonTriangulation/file/46627373148/issues/source?bid=19134932&fileBranchId=19134932#l980)

See also my original issue on [sonar-dotnet](https://github.com/SonarSource/sonar-dotnet/issues/3446), which is already closed.

**Comment by josemiguelmelo** [comment]
Hi @git-ruttmann 

At Codacy, we do an incremental analysis on the project. Consequently, we use the commit diff to know which files changed and which files should be analysed. 
This means we analyse only the changed files and that’s the reason why we make this analysis file by file.

Unfortunately, these false positives are being thrown because we are not analysing the entire project for every commit.

We are currently working to find a possible solution for this problem.
However, for now I guess the only option to avoid these false positives is to disable the patterns.

**Comment by josemiguelmelo** [comment]
Hi,

Unfortunately, we still maintain the limitation of incremental analysis when analysing a commit, which may return false positives. To prevent these false positives from happening, we decided to disable these patterns from our list of supported patterns.

We're working on ways to give you more flexibility on how these tools are run. And we'll take this into consideration for our next steps.
I hope we can come back to you soon with good news about this 🙂

Thanks,
